Hw03 mongodb
Mharkov/nodejs-homework-rest-api pull request #1
Opened 2021-05-18 19:27 UTC by Mharkov

2021-05-18 19:47 UTC, SergeiKBB requested changes

2021-05-18 19:47 UTC, SergeiKBB commented on .env
> +URI_DB=mongodb+srv://GoitNode:09871234@clusternode.zmwde.mongodb.net/db-contacts?retryWrites=true&w=majority
файл должен быть добавлен в гитогноре

2021-05-19 20:39 UTC, SergeiKBB commented on .env
> +URI_DB=mongodb+srv://GoitNode:09871234@clusternode.zmwde.mongodb.net/db-contacts?retryWrites=true&w=majority
файл все ещё сдесь. Он должен быть удален с ремоут репозитория

2021-05-20 04:38 UTC, Mharkov commented on .env
> +URI_DB=mongodb+srv://GoitNode:09871234@clusternode.zmwde.mongodb.net/db-contacts?retryWrites=true&w=majority
Всё сделал. Думал что после пул реквеста он уйдет. Внёс же в гитигнор.
Сделал что удали файл записал коммит после внёс его в проект
Теперь вроде норм

2021-05-21 12:11 UTC, SergeiKBB approved these changes

2021-05-26 07:39 UTC, merged